"""Tests for parquet_cache module — DuckDB + Parquet cache lifecycle."""

import json
import os

from nsys_ai import parquet_cache


class TestCacheValidation:
    """Test cache validity checks."""

    def test_no_cache_dir(self, tmp_path):
        fake_sqlite = str(tmp_path / "profile.sqlite")
        open(fake_sqlite, "w").close()
        assert parquet_cache.is_cache_valid(fake_sqlite) is False

    def test_empty_cache_dir(self, tmp_path):
        fake_sqlite = str(tmp_path / "profile.sqlite")
        open(fake_sqlite, "w").close()
        (tmp_path / "profile.nsys-cache").mkdir()
        assert parquet_cache.is_cache_valid(fake_sqlite) is False

    def test_wrong_version(self, tmp_path):
        fake_sqlite = str(tmp_path / "profile.sqlite")
        open(fake_sqlite, "w").close()
        cache_dir = tmp_path / "profile.nsys-cache"
        cache_dir.mkdir()
        (cache_dir / ".cache_version").write_text(json.dumps({"version": -1}))
        (cache_dir / "kernels.parquet").write_text("dummy")
        assert parquet_cache.is_cache_valid(fake_sqlite) is False


class TestBuildAndOpen:
    """End-to-end: build cache from test SQLite, then open."""

    def test_build_cache_creates_parquet_files(self, minimal_nsys_db_path):
        """Building a cache should create Parquet files in .nsys-cache/."""
        cache_dir = parquet_cache.build_cache(minimal_nsys_db_path)

        assert cache_dir.exists()
        assert (cache_dir / "kernels.parquet").exists()
        assert (cache_dir / "nvtx.parquet").exists()
        assert (cache_dir / "runtime.parquet").exists()
        assert (cache_dir / ".cache_version").exists()

        # Version stamp
        meta = json.loads((cache_dir / ".cache_version").read_text())
        assert meta["version"] == parquet_cache._CACHE_VERSION

    def test_cache_is_valid_after_build(self, minimal_nsys_db_path):
        """After building, is_cache_valid should return True."""
        parquet_cache.build_cache(minimal_nsys_db_path)
        assert parquet_cache.is_cache_valid(minimal_nsys_db_path) is True

    def test_open_cached_db_returns_duckdb(self, minimal_nsys_db_path):
        """open_cached_db should return a DuckDB connection with views."""
        import duckdb

        db = parquet_cache.open_cached_db(minimal_nsys_db_path)
        assert isinstance(db, duckdb.DuckDBPyConnection)

        # Should be able to query kernels
        result = db.execute("SELECT COUNT(*) FROM kernels").fetchone()
        assert result[0] > 0

        db.close()

    def test_kernel_names_resolved(self, minimal_nsys_db_path):
        """Kernels parquet should have pre-joined name column."""
        db = parquet_cache.open_cached_db(minimal_nsys_db_path)
        rows = db.execute("SELECT name FROM kernels WHERE name IS NOT NULL").fetchall()
        assert len(rows) > 0
        # At least one kernel should have a resolved name
        names = [r[0] for r in rows]
        assert any(n for n in names if n)
        db.close()

    def test_nvtx_kernel_map_generated(self, minimal_nsys_db_path):
        """nvtx_kernel_map.parquet should be generated by Tier 2 sort-merge."""
        cache_dir = parquet_cache.build_cache(minimal_nsys_db_path)
        map_file = cache_dir / "nvtx_kernel_map.parquet"
        # It's OK if it doesn't exist (if no NVTX→kernel attribution found)
        # but if it does, it should be queryable
        if map_file.exists():
            dict_file = cache_dir / "nvtx_path_dict.parquet"
            assert dict_file.is_file()
            db = parquet_cache.open_cached_db(minimal_nsys_db_path)
            result = db.execute(
                """
                SELECT m.path_id, d.nvtx_path
                FROM nvtx_kernel_map m
                JOIN nvtx_path_dict d USING (path_id)
                LIMIT 5
                """
            )
            joined = result.fetchall()
            assert isinstance(joined, list)
            assert [col[0] for col in result.description] == ["path_id", "nvtx_path"]
            if joined:
                assert len(joined[0]) == 2
                assert isinstance(joined[0][0], int)
                assert joined[0][1] is None or isinstance(joined[0][1], str)
            db.close()

    def test_invalidate_cache(self, minimal_nsys_db_path):
        """invalidate_cache should remove the cache directory."""
        parquet_cache.build_cache(minimal_nsys_db_path)
        assert parquet_cache.is_cache_valid(minimal_nsys_db_path) is True

        parquet_cache.invalidate_cache(minimal_nsys_db_path)
        assert parquet_cache.is_cache_valid(minimal_nsys_db_path) is False

    def test_rebuild_on_stale(self, minimal_nsys_db_path):
        """If SQLite is newer than cache, rebuild automatically."""
        parquet_cache.build_cache(minimal_nsys_db_path)
        assert parquet_cache.is_cache_valid(minimal_nsys_db_path) is True

        # Touch the SQLite to make it newer; sleep long enough to exceed
        # coarse filesystem mtime granularity (often 1s).
        import time

        time.sleep(1.1)
        os.utime(minimal_nsys_db_path, None)

        assert parquet_cache.is_cache_valid(minimal_nsys_db_path) is False

        # open_cached_db should auto-rebuild
        db = parquet_cache.open_cached_db(minimal_nsys_db_path)
        assert db is not None
        db.close()
        assert parquet_cache.is_cache_valid(minimal_nsys_db_path) is True
