"""Tests for parquet_cache module — DuckDB + Parquet cache lifecycle."""

import json
import os
from pathlib import Path

import pytest

from nsys_ai import parquet_cache


class TestCacheValidation:
    """Test cache validity checks."""

    def test_no_cache_dir(self, tmp_path):
        fake_sqlite = str(tmp_path / "profile.sqlite")
        open(fake_sqlite, "w").close()
        assert parquet_cache.is_cache_valid(fake_sqlite) is False

    def test_empty_cache_dir(self, tmp_path):
        fake_sqlite = str(tmp_path / "profile.sqlite")
        open(fake_sqlite, "w").close()
        (tmp_path / "profile.nsys-cache").mkdir()
        assert parquet_cache.is_cache_valid(fake_sqlite) is False

    def test_wrong_version(self, tmp_path):
        fake_sqlite = str(tmp_path / "profile.sqlite")
        open(fake_sqlite, "w").close()
        cache_dir = tmp_path / "profile.nsys-cache"
        cache_dir.mkdir()
        (cache_dir / ".cache_version").write_text(json.dumps({"version": -1}))
        (cache_dir / "kernels.parquet").write_text("dummy")
        assert parquet_cache.is_cache_valid(fake_sqlite) is False


class TestBuildAndOpen:
    """End-to-end: build cache from test SQLite, then open."""

    def test_build_cache_creates_parquet_files(self, minimal_nsys_db_path):
        """Building a cache should create Parquet files in .nsys-cache/."""
        cache_dir = parquet_cache.build_cache(minimal_nsys_db_path)

        assert cache_dir.exists()
        assert (cache_dir / "kernels.parquet").exists()
        assert (cache_dir / "nvtx.parquet").exists()
        assert (cache_dir / "runtime.parquet").exists()
        assert (cache_dir / ".cache_version").exists()

        # Version stamp
        meta = json.loads((cache_dir / ".cache_version").read_text())
        assert meta["version"] == parquet_cache._CACHE_VERSION

    def test_cache_is_valid_after_build(self, minimal_nsys_db_path):
        """After building, is_cache_valid should return True."""
        parquet_cache.build_cache(minimal_nsys_db_path)
        assert parquet_cache.is_cache_valid(minimal_nsys_db_path) is True

    def test_open_cached_db_returns_duckdb(self, minimal_nsys_db_path):
        """open_cached_db should return a DuckDB connection with views."""
        import duckdb

        db = parquet_cache.open_cached_db(minimal_nsys_db_path)
        assert isinstance(db, duckdb.DuckDBPyConnection)

        # Should be able to query kernels
        result = db.execute("SELECT COUNT(*) FROM kernels").fetchone()
        assert result[0] > 0

        db.close()

    def test_kernel_names_resolved(self, minimal_nsys_db_path):
        """Kernels parquet should have pre-joined name column."""
        db = parquet_cache.open_cached_db(minimal_nsys_db_path)
        rows = db.execute("SELECT name FROM kernels WHERE name IS NOT NULL").fetchall()
        assert len(rows) > 0
        # At least one kernel should have a resolved name
        names = [r[0] for r in rows]
        assert any(n for n in names if n)
        db.close()

    def test_nvtx_kernel_map_generated(self, minimal_nsys_db_path):
        """nvtx_kernel_map.parquet should be generated by Tier 2 sort-merge."""
        cache_dir = parquet_cache.build_cache(minimal_nsys_db_path)
        map_file = cache_dir / "nvtx_kernel_map.parquet"
        # It's OK if it doesn't exist (if no NVTX→kernel attribution found)
        # but if it does, it should be queryable
        if map_file.exists():
            dict_file = cache_dir / "nvtx_path_dict.parquet"
            assert dict_file.is_file()
            db = parquet_cache.open_cached_db(minimal_nsys_db_path)
            result = db.execute(
                """
                SELECT m.path_id, d.nvtx_path
                FROM nvtx_kernel_map m
                JOIN nvtx_path_dict d USING (path_id)
                LIMIT 5
                """
            )
            joined = result.fetchall()
            assert isinstance(joined, list)
            assert [col[0] for col in result.description] == ["path_id", "nvtx_path"]
            if joined:
                assert len(joined[0]) == 2
                assert isinstance(joined[0][0], int)
                assert joined[0][1] is None or isinstance(joined[0][1], str)
            db.close()

    def test_invalidate_cache(self, minimal_nsys_db_path):
        """invalidate_cache should remove the cache directory."""
        parquet_cache.build_cache(minimal_nsys_db_path)
        assert parquet_cache.is_cache_valid(minimal_nsys_db_path) is True

        parquet_cache.invalidate_cache(minimal_nsys_db_path)
        assert parquet_cache.is_cache_valid(minimal_nsys_db_path) is False

    def test_rebuild_on_stale(self, minimal_nsys_db_path):
        """If SQLite is newer than cache, rebuild automatically."""
        parquet_cache.build_cache(minimal_nsys_db_path)
        assert parquet_cache.is_cache_valid(minimal_nsys_db_path) is True

        # Touch the SQLite to make it newer; sleep long enough to exceed
        # coarse filesystem mtime granularity (often 1s).
        import time

        time.sleep(1.1)
        os.utime(minimal_nsys_db_path, None)

        assert parquet_cache.is_cache_valid(minimal_nsys_db_path) is False

        # open_cached_db should auto-rebuild
        db = parquet_cache.open_cached_db(minimal_nsys_db_path)
        assert db is not None
        db.close()
        assert parquet_cache.is_cache_valid(minimal_nsys_db_path) is True


class TestConcurrentBuild:
    """Regression: two terminals opening the same profile concurrently
    must NOT both run the full ETL.

    Before the build-lock landed, ``is_cache_valid()`` returned False
    for every concurrent caller until the first finished its atomic
    rename, so every caller ran its own ``_build_cache_into``. On a
    296MB profile that meant ~10s of wasted ETL per duplicate runner.
    """

    @pytest.mark.skipif(
        parquet_cache._fcntl is None,
        reason="build-lock degrades to no-op without POSIX fcntl; this assertion "
        "only holds on platforms where the lock is real.",
    )
    def test_concurrent_threads_only_build_once(self, minimal_nsys_db_path, monkeypatch):
        import threading
        import time

        # Start clean — make sure no prior test left a valid cache for
        # this fixture (the cache lives next to the .sqlite file).
        parquet_cache.invalidate_cache(minimal_nsys_db_path)
        assert parquet_cache.is_cache_valid(minimal_nsys_db_path) is False

        num_threads = 4
        # Barrier so every runner enters ``build_cache`` essentially
        # simultaneously — without this, on lightly-loaded systems the
        # first thread can finish before the others even start, hiding
        # any locking bug.
        barrier = threading.Barrier(num_threads)
        call_count = 0
        count_lock = threading.Lock()
        original_build_into = parquet_cache._build_cache_into

        def counting_build_into(sqlite_path: str, tmp_dir: Path) -> None:
            nonlocal call_count
            with count_lock:
                call_count += 1
            # Hold the lock long enough that all other threads are
            # guaranteed to be queued on flock before this one releases.
            # ETL on the minimal fixture is ~50ms; 0.5s sleep gives a
            # ~10× safety margin.
            time.sleep(0.5)
            original_build_into(sqlite_path, tmp_dir)

        monkeypatch.setattr(parquet_cache, "_build_cache_into", counting_build_into)

        # Track caches and exceptions separately so a barrier timeout
        # or any other error can't masquerade as "all paths succeeded".
        caches: list[Path] = []
        errors: list[BaseException] = []
        results_lock = threading.Lock()

        def runner() -> None:
            try:
                barrier.wait(timeout=10)
                cache = parquet_cache.build_cache(str(minimal_nsys_db_path))
            except BaseException as e:  # pragma: no cover - defensive
                with results_lock:
                    errors.append(e)
                return
            with results_lock:
                caches.append(cache)

        threads = [threading.Thread(target=runner) for _ in range(num_threads)]
        for t in threads:
            t.start()
        for t in threads:
            t.join(timeout=30)

        # If any thread is still alive the lock has deadlocked.
        # Surface that immediately rather than letting a zombie thread
        # leak into later tests where it could rebuild the cache and
        # confuse unrelated assertions.
        stuck = [t.name for t in threads if t.is_alive()]
        assert not stuck, f"threads did not finish within 30s: {stuck}"

        assert errors == [], f"runners raised: {errors!r}"
        assert len(caches) == num_threads, (
            f"all {num_threads} runners must complete; got {len(caches)}"
        )
        assert call_count == 1, (
            f"_build_cache_into should run exactly once for {num_threads} "
            f"concurrent callers; got {call_count}"
        )
        # Every caller returns the same cache directory.
        assert len(set(caches)) == 1, f"all callers must agree on cache_dir; got {set(caches)}"
        assert parquet_cache.is_cache_valid(minimal_nsys_db_path) is True


class TestTensorCorePatterns:
    """Regression coverage for the TC eligibility / active regex patterns.

    The patterns are interpolated into DuckDB `regexp_matches()`; these cases
    guard against drift that would cause Flash Attention / CUTLASS tensor-op
    kernels to be silently mis-classified as FP32 fallback.
    """

    @staticmethod
    def _strip(pattern: str) -> str:
        # Stored as SQL-quoted literal, e.g. "'(gemm|...)'" — strip the outer quotes
        # so Python's re module sees a plain pattern.
        return pattern.strip("'")

    def test_eligible_pattern_covers_flash_attention(self):
        import re

        elig = self._strip(parquet_cache._TC_ELIGIBLE_PATTERN)
        for name in [
            "flash_fwd_splitkv_kernel",
            "flash_bwd_dq_dk_dv_loop_seqk_parallel",
            "ampere_bf16_s1688gemm_bf16_128x128x32",
            "cutlass_80_tensorop_bf16_s16816gemm_something",
            "sm80_xmma_gemm_bf16",
        ]:
            assert re.search(elig, name.lower()), f"{name!r} should be TC-eligible"

    def test_active_pattern_covers_cutlass_and_flash(self):
        import re

        active = self._strip(parquet_cache._TC_ACTIVE_PATTERN)
        for name in [
            "flash_fwd_splitkv_kernel",
            "flash_bwd_dq_dk_dv_loop_seqk_parallel",
            "cutlass_80_tensorop_bf16_s16816gemm_something",
            "ampere_bf16_s1688gemm_bf16_128x128x32",
            "some_kernel_with_16816_in_name",
        ]:
            assert re.search(active, name.lower()), f"{name!r} should be TC-active"

    def test_non_tc_kernels_not_matched(self):
        import re

        elig = self._strip(parquet_cache._TC_ELIGIBLE_PATTERN)
        active = self._strip(parquet_cache._TC_ACTIVE_PATTERN)
        for name in [
            "vectorized_elementwise_kernel",
            "reduce_kernel",
            "memset_kernel",
        ]:
            assert not re.search(elig, name.lower()), f"{name!r} should NOT be eligible"
            assert not re.search(active, name.lower()), f"{name!r} should NOT be active"

    def test_fp32_sgemm_is_eligible_but_not_tc_active(self):
        """Classic FP32 sgemm: TC-eligible (it's a gemm) but not TC-active."""
        import re

        elig = self._strip(parquet_cache._TC_ELIGIBLE_PATTERN)
        active = self._strip(parquet_cache._TC_ACTIVE_PATTERN)
        name = "ampere_sgemm_128x128_nn"
        assert re.search(elig, name.lower())
        assert not re.search(active, name.lower())
